name: CI

on: [push]

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm install

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
        run: npm test

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run e2e tests
        run: npm run test:e2e

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: npm run build
