name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install && npm run lint

  unit-tests:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: npm run test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [lint, unit-tests]

    steps:
      - uses: actions/checkout@v3
      - name: Run e2e tests
        run: npm run test:e2e

  build:
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, e2e-tests]

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: npm run build
